# -*- coding: utf-8 -*-
"""Air-Quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Shervinrtd/Air-Quality/blob/main/Air-Quality.ipynb

# Predicting Extreme Air Pollution Levels Using PySpark

###  Project Overview
This project uses Apache Spark and PySpark to analyze and predict extreme air pollution levels across monitoring stations in the United States.

The primary target objective is to predict the **99th Percentile** pollution concentration value using geographical, observational metadata, and statistical summaries compiled from monitoring stations. This allows for the identification and evaluation of severe environmental risk configurations without relying on hourly sequential datasets.

The implementation builds a complete distributed data pipeline covering:
- Large-scale dataset ingestion, schema validation, and distributed column standardization
- Handling high-cardinality categorical attributes via StringIndexing and OneHotEncoding
- Assembly and normalization of multi-scale continuous indicators
- Execution of automated Spark ML Pipelines
- Training, tuning, and evaluation of 6 distinct distributed machine learning algorithms
- visual evaluation of predicted variance

---

###  Required Environment & Library Versions
*Per Section 3 of the course syllabus guidelines, the required execution environment and matching software versions are specified below:*

- **Python Runtime:** Version 3.10+
- **Apache Spark / PySpark:** Version 3.5.0+
- **Java Development Kit (JDK):** Version 11+
- **Pandas Data Analysis Library:** Version 2.0+
- **Matplotlib Visualization Library:** Version 3.7+
- **Seaborn Statistical Visualization:** Version 0.12+

---

###  Dataset Scale Metrics & Core Parameters
This project strictly satisfies all dataset volume constraints defined in the course instructions:
* **Number of patterns ($N$):** 58,745 rows (Satisfies $N \geq 20,000$)
* **Number of base predictors ($p$):** 18 distinct features (16 continuous/numerical features + 2 high-cardinality categorical variables)
* **Number of algorithms ($n_\mathcal{A}$):** 6 ML algorithms (Satisfies requirements for combined presentation)
* **Syllabus Scaling Product ($N \times p$):** **1,057,410** (Satisfies the constraint $N \times p \geq 1,000,000$)

---

###  Employed Machine Learning Algorithms
To comprehensively analyze the data structure and handle the high-dimensional feature vectors produced after categorical expansion, the pipeline evaluates and compares six distributed regression architectures:

1. **Standard Linear Regression (Ordinary Least Squares)**
2. **Generalized Linear Regression (GLR - Gamma family with Log link):**
The Gamma GLR was selected because pollution concentration variables are strictly positive and exhibit right-skewed distributions. The logarithmic link function allows multiplicative environmental effects to be modeled more naturally than Gaussian assumptions.
3. **Linear Support Vector Regression (LinearSVR)**
4. **Elastic Net Regression (Linear model with combined $L_1$ and $L_2$ regularizations)**
5. **Random Forest Regressor (Ensemble Bagging architecture)**
6. **Gradient-Boosted Tree (GBT) Regressor (Ensemble Boosting architecture)**

---

###  Target & Prediction Feature Breakdown
- **Target Variable:** `99th Percentile` concentration level.
- **Continuous Features ($p_{num} = 16$):** `Arithmetic Mean`, `Arithmetic Standard Dev`, `1st Max Value`, `2nd Max Value`, `3rd Max Value`, `4th Max Value`, `Observation Count`, `Observation Percent`, `Valid Day Count`, `Required Day Count`, `Exceptional Data Count`, `Null Data Count`, `Latitude`, `Longitude`, `50th Percentile`, `10th Percentile`.
- **Categorical Features ($p_{cat} = 2$):** `State Name`, `Parameter Name` (processed into sparse multi-dimensional dummy arrays using `OneHotEncoder`).

---

###  Data Access & Reproducibility
The dataset is stored and accessed through Hadoop Distributed File System (HDFS). Spark reads the distributed CSV dataset directly from HDFS, enabling scalable processing within the VM-based distributed environment.
"""

import sys
import re
import pyspark
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pyspark.sql import SparkSession
from pyspark.ml import Pipeline
from pyspark.ml.feature import StringIndexer, OneHotEncoder, VectorAssembler, StandardScaler
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.ml.tuning import ParamGridBuilder, TrainValidationSplit
from pyspark.ml.regression import (
    LinearRegression,
    GeneralizedLinearRegression,
    RandomForestRegressor,
    GBTRegressor,
    LinearSVR
)

print("Python Version:", sys.version)
print("PySpark Version:", pyspark.__version__)
print("Pandas Version:", pd.__version__)

"""##  Create Spark Session"""

spark = SparkSession.builder \
    .appName("AirQualityPrediction") \
    .getOrCreate()

print("Spark Session Created")

print("===== HADOOP + SPARK ENVIRONMENT INITIALIZED =====")
print("Reading dataset from HDFS...")

"""## Distributed Dataset Loading from HDFS

The dataset is stored inside Hadoop Distributed File System (HDFS) and loaded through Apache Spark using distributed storage access. This replaces local filesystem loading and enables scalable Big Data processing.

## Load Dataset into Spark
"""

# Load dataset into Spark

df = spark.read.csv(
    "hdfs:///datasets/annual_conc_by_monitor_2025.csv",
    header=True,
    inferSchema=True
)

print("Rows:", df.count())
print("Columns:", len(df.columns))

df.show(5)

"""## Clean Column Names"""

# Clean and standardize column names
clean_columns = []

for c in df.columns:

    # Remove leading/trailing spaces
    c = c.strip()

    # Replace multiple spaces with single space
    c = re.sub(r"\s+", " ", c)

    clean_columns.append(c)

# Apply cleaned names
df = df.toDF(*clean_columns)

# Isolate target, categoricals, and the filtered non-leaking features
selected_df = df.select(
    "State Name",
    "Parameter Name",
    "99th Percentile",
    "Arithmetic Mean",
    "Arithmetic Standard Dev",
    "1st Max Value",
    "2nd Max Value",
    "3rd Max Value",
    "4th Max Value",
    "Observation Count",
    "Observation Percent",
    "Valid Day Count",
    "Required Day Count",
    "Exceptional Data Count",
    "Null Data Count",
    "Latitude",
    "Longitude",
    "50th Percentile",
    "10th Percentile"
)

"""##  Remove Unnecessary Columns"""

# Drop nulls AND filter out non-positive target labels to prevent GLR Gamma runtime crashes
clean_df = selected_df.dropna().filter("`99th Percentile` > 0")

"""##  Define Feature Columns

## Feature Engineering

The model uses both continuous environmental statistics and encoded categorical variables. Numerical variables represent pollution measurements and monitoring statistics, while categorical variables (State and Pollutant Parameter) are transformed using StringIndexer and OneHotEncoder.
"""

target_column = "99th Percentile"

# Standard Base Feature
base_features = [
    "Arithmetic Mean", "Arithmetic Standard Dev", "1st Max Value", "2nd Max Value",
    "3rd Max Value", "4th Max Value", "Observation Count", "Observation Percent",
    "Valid Day Count", "Required Day Count", "Exceptional Data Count", "Null Data Count",
    "Latitude", "Longitude", "50th Percentile", "10th Percentile"
]

print(f"Number of rows (N): {clean_df.count()}")
print(f"Number of base predictors (p): {len(base_features) + 2}")
print(f"Syllabus Product (N * p): {clean_df.count() * (len(base_features) + 2)}")

"""##  Encode Categorical Features"""

# Instantiating Feature Preprocessing Stages (Wired cleanly to protect against Data Leakage)
parameter_indexer = StringIndexer(inputCol="Parameter Name", outputCol="ParameterIndex", handleInvalid="keep")
state_indexer = StringIndexer(inputCol="State Name", outputCol="StateIndex", handleInvalid="keep")
encoder = OneHotEncoder(inputCols=["StateIndex", "ParameterIndex"], outputCols=["StateVec", "ParameterVec"])

"""#  Standardize ONLY continuous features to preserve sparse matrix efficiency"""

continuous_assembler = VectorAssembler(inputCols=base_features, outputCol="continuous_features")
scaler = StandardScaler(inputCol="continuous_features", outputCol="scaled_continuous_features", withMean=True, withStd=True)

"""##  Train/Test Split
The dataset consists of aggregated annual monitoring summaries rather than sequential hourly observations. Therefore, random partitioning was selected instead of chronological splitting because rows are treated as independent annual statistical records.
"""

train_data, test_data = clean_df.randomSplit(
    [0.8, 0.2],
    seed=42
)

print("Training Rows:", train_data.count())
print("Testing Rows:", test_data.count())

"""# Build feature vector configurations specialized per model type"""

print("\n===== DISTRIBUTED PREPROCESSING =====")
# Fit text metadata transformations AND feature scaling ONCE on train_data to prevent data leakage
preprocessing_pipeline = Pipeline(stages=[
    parameter_indexer,
    state_indexer,
    encoder,
    continuous_assembler,
    scaler
])
preprocessing_model = preprocessing_pipeline.fit(train_data)

# Transform datasets upfront and invoke .cache() to pin them into cluster RAM
preprocessed_train = preprocessing_model.transform(train_data).cache()
preprocessed_test = preprocessing_model.transform(test_data).cache()

# Trigger an action to force caching execution immediately
print(f"Cached Training DataFrame Size: {preprocessed_train.count()} rows.")
print(f"Cached Testing DataFrame Size: {preprocessed_test.count()} rows.")

# Build feature vector configurations specialized per model family
# Linear/SVR architectures get standardized features combined with one-hot sparse matrices
linear_assembler = VectorAssembler(inputCols=["scaled_continuous_features", "StateVec", "ParameterVec"], outputCol="features")

# Tree architectures receive raw unscaled features combined with integer indexes (optimized for tree splits)
tree_assembler = VectorAssembler(inputCols=base_features + ["StateIndex", "ParameterIndex"], outputCol="features")

evaluator_rmse = RegressionEvaluator(
    labelCol=target_column,
    predictionCol="prediction",
    metricName="rmse"
)

evaluator_r2 = RegressionEvaluator(
    labelCol=target_column,
    predictionCol="prediction",
    metricName="r2"
)

print(" FEATURE ASSEMBLER AND EVALUATORS CONFIGURED ")

"""# Initialize base models for clear grid parameter references"""

elastic_net_base = LinearRegression(featuresCol="features", labelCol=target_column)
gbt_base = GBTRegressor(featuresCol="features", labelCol=target_column, maxBins=256, seed=42)

# Build Hyperparameter Exploration Grids (Fulfills strict syllabus parameter testing guidelines)
grid_elastic_net = ParamGridBuilder() \
    .addGrid(elastic_net_base.regParam, [0.01, 0.1, 0.5]) \
    .addGrid(elastic_net_base.elasticNetParam, [0.2, 0.5, 0.8]) \
    .build()

grid_gbt = ParamGridBuilder() \
    .addGrid(gbt_base.maxDepth, [5, 10]) \
    .addGrid(gbt_base.maxIter, [20, 50]) \
    .build()

"""##  Build Machine Learning Pipeline"""

# Advanced Model Configuration Registry
models_config = {
    "Standard Linear Regression": {
        "algo": LinearRegression(featuresCol="features", labelCol=target_column),
        "assembler": linear_assembler,
        "param_grid": None
    },
    "Elastic Net Regression (TUNED)": {
        "algo": elastic_net_base,
        "assembler": linear_assembler,
        "param_grid": grid_elastic_net
    },
    "Generalized Linear Regression (Gamma)": {
        "algo": GeneralizedLinearRegression(family="gamma", link="log", featuresCol="features", labelCol=target_column),
        "assembler": linear_assembler,
        "param_grid": None
    },
    "Linear SVR": {
        "algo": LinearSVR(featuresCol="features", labelCol=target_column, maxIter=100),
        "assembler": linear_assembler,
        "param_grid": None
    },
    "Random Forest": {
        "algo": RandomForestRegressor(featuresCol="features", labelCol=target_column, numTrees=100, maxDepth=10, maxBins=256, seed=42),
        "assembler": tree_assembler,
        "param_grid": None
    },
    "Gradient-Boosted Tree (TUNED)": {
        "algo": gbt_base,
        "assembler": tree_assembler,
        "param_grid": grid_gbt
    }
}

results = {}
print("\nExecuting Distributed Machine Learning Pipeline Operations...")

for model_name, config in models_config.items():
    print(f"\nProcessing Architecture Block: {model_name}")

    # Construct base evaluation pipeline
    base_pipeline = Pipeline(stages=[config["assembler"], config["algo"]])

    # Conditional execution pathway: If tuning grid exists, execute holdout search harness
    if config["param_grid"] is not None:
        print(f" -> Tuning Enabled. Initiating TrainValidationSplit exploration harness...")
        tvs = TrainValidationSplit(
            estimator=base_pipeline,
            estimatorParamMaps=config["param_grid"],
            evaluator=evaluator_rmse,
            trainRatio=0.8,
            seed=42
        )
        trained_model = tvs.fit(preprocessed_train)

        # Extract and print the best hyperparameter configuration for your slides
        best_pipeline_model = trained_model.bestModel
        best_algo_stage = best_pipeline_model.stages[-1]

        print(f" TUNING COMPLETE FOR {model_name} ")
        if "Elastic Net" in model_name:
            print(f"   -> Selected Optimal regParam: {best_algo_stage.getRegParam()}")
            print(f"   -> Selected Optimal elasticNetParam: {best_algo_stage.getElasticNetParam()}")
        elif "Gradient-Boosted Tree" in model_name:
            print(f"   -> Selected Optimal maxDepth: {best_algo_stage.getMaxDepth()}")
            print(f"   -> Selected Optimal maxIter: {best_algo_stage.getMaxIter()}")
    else:
        print(f" -> Baseline Mode. Fitting static pipeline architecture parameters...")
        trained_model = base_pipeline.fit(preprocessed_train)

    # Generate predictive rows from the held-out test partition
    predictions = trained_model.transform(preprocessed_test)

    # Compute metrics out of the distributed prediction evaluation stream
    results[model_name] = {
        "RMSE": evaluator_rmse.evaluate(predictions),
        "R2": evaluator_r2.evaluate(predictions)
    }

"""##  Final Model Comparison"""

print("\n" + "="*50)
print("  FINAL DISTRIBUTION MODEL COMPARISON  ")
print("="*50)

sorted_results = dict(sorted(results.items(), key=lambda item: item[1]['R2'], reverse=True))

for name, metrics in sorted_results.items():
    print(f"{name}:")
    print(f"  -> R² Variance Explained: {metrics['R2']:.4f}")
    print(f"  -> Residual Error (RMSE): {metrics['RMSE']:.4f}\n")

print(" GENERATING PERFORMANCE VISUALIZATIONS ")

plot_data = [{"Model": k, "R2": v["R2"], "RMSE": v["RMSE"]} for k, v in sorted_results.items()]
df_results = pd.DataFrame(plot_data)

sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.barplot(x="R2", y="Model", data=df_results, ax=axes[0], palette="viridis")
axes[0].set_title("Model Comparison: R² Fit Performance", fontsize=12, fontweight='bold')
axes[0].set_xlabel("R² Score", fontsize=10)
axes[0].set_ylabel("")
axes[0].set_xlim(0, 1.05)

sns.barplot(x="RMSE", y="Model", data=df_results, ax=axes[1], palette="magma")
axes[1].set_title("Model Comparison: Prediction Residuals (RMSE)", fontsize=12, fontweight='bold')
axes[1].set_xlabel("RMSE", fontsize=10)
axes[1].set_ylabel("")

plt.tight_layout()
plt.savefig("model_comparison.png", dpi=300, bbox_inches='tight')
print("Success! Performance charts saved locally as 'model_comparison.png'.")

preprocessed_train.unpersist()
preprocessed_test.unpersist()

"""## Distributed Execution Environment

This project was executed inside a Linux Virtual Machine using Apache Hadoop HDFS and Apache Spark. The dataset was stored in HDFS and processed through PySpark MLlib pipelines, satisfying the distributed infrastructure requirements of Big Data Analytics workflows.
"""